/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package QuanLySach;

import Database.DAOLoaiSach;
import Database.DAONXB;
import Database.DAOSach;
import Object.LoaiSach;
import Object.NXB;
import Object.Sach;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author AUGUST
 */

public class CacLoaiSach extends javax.swing.JFrame {
    DAOLoaiSach daoloaisach = new DAOLoaiSach();
//    DAONXB daonxb = new DAONXB();
//    DAOSach daosach = new DAOSach();
    private DefaultTableModel tableModel;//được sử dụng để định nghĩa cấu trúc của bảng và lưu trữ dữ liệu,Cung cấp các pt CRUD;
    private List<LoaiSach>ListLS;
    public int selectedIndex;
    DecimalFormat decimalformat = new DecimalFormat("###,###,###");
    /**
     * Creates new form CacLoaiSach
     */
    public CacLoaiSach() {
        initComponents();//để khởi tạo giao diện jframe
        setLocationRelativeTo(null);//được sử dụng để đặt vị trí của cửa sổ tương đối với màn hình
        ListLS = DAOLoaiSach.getListLoaiSach();
        tableModel = (DefaultTableModel) tbLoaiSach.getModel();
        HienThiLoaiSach();
//        getCBNXB();
//        getComboLoaiSach();
        
        
    }
//    public void getCBNXB(){
//        DefaultComboBoxModel cboModel = (DefaultComboBoxModel) cbNhaXuatBan.getModel();
//        for(NXB nxb : daonxb.getListNXB()){
//            cboModel.addElement(nxb);
//        }
//    }
//    public void getComboLoaiSach(){
//        DefaultComboBoxModel cboModel = (DefaultComboBoxModel) cbLoaiSach.getModel();
//        for(Sach s : daosach.getListSach()){
//            cboModel.addElement(s);
//        }
//    }
    public void HienThiLoaiSach(){
    ListLS = DAOLoaiSach.getListLoaiSach();
    tableModel.setRowCount(0);
    
    for(LoaiSach ls : ListLS){
        //ham for-each duyet qua cac pt ma khong can index;
        //Dữ liệu được thêm vào bằng cách sử dụng addRow
        tableModel.addRow(new Object[]{ls.getID(), ls.getMaSach(), ls.getTenSach(), decimalformat.format(ls.getDonGia()) + "đ", ls.getSoLuong(), ls.getNgayXuatBan(), ls.getLoaiSach(), ls.getNhaXuatBan()});
    }
    tableModel.fireTableDataChanged();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        tbLoaiSach = new javax.swing.JTable();
        btnTimKiem = new javax.swing.JButton();
        btnQuayLai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Quản Lý Các Loại Sách");

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        tbLoaiSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "MaSach", "TenSach", "Gia", "SoLuong", "NgayXuatBan", "LoaiSach", "NhaXuatBan"
            }
        ));
        tbLoaiSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbLoaiSachMouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(tbLoaiSach);

        btnTimKiem.setText("Tìm Kiếm Theo Tên");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnQuayLai.setText("Form Quản Lý");
        btnQuayLai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(514, 514, 514)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(btnQuayLai, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(185, Short.MAX_VALUE))
            .addComponent(jScrollPane9, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnQuayLai, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(45, 45, 45)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(338, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
    System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        
//        if (txtMaSach.getText().equals("") || txtTenSach.getText().equals("") || txtDonGia.getText().equals("") || txtSoLuong.getText().equals("") || txtNgayXuatBan.getText().equals("")) {
//            JOptionPane.showMessageDialog(this, "vui lòng nhập đầy đủ thông tin !!! ");
//        } else {
//            
//             int ID = Integer.parseInt(txtID.getText());
//             LoaiSach ls = new LoaiSach(MaSach , TenSach, DonGia, SoLuong, NgayXuatBan, LoaiSach, NhaXuatBan);
//             ls.setID(Integer.parseInt(txtID.getText()));
//             txtID.setEditable(false);
//             txtMaSach.setText(ls.getMaSach());
//             txtTenSach.setText(ls.getTenSach());
//             txtDonGia.setText(formatter.format(ls.getDonGia())+"đ");
//             txtSoLuong.setText(Integer.toString(ls.getSoLuong()));
//             txtNgayXuatBan.setText(ls.getNgayXuatBan());
//             cbLoaiSach.setSelectedItem(ls.getLoaiSach());
//             cbNhaXuatBan.setSelectedItem(ls.getNgayXuatBan());
               
//            try {
//                DAOLoaiSach.InsertLoaiSach(ls);
//            } catch (SQLException ex) {
//                Logger.getLogger(CacLoaiSach.class.getName()).log(Level.SEVERE, null, ex);
//                JOptionPane.showMessageDialog(this, "them ko thanh cong");
//            }
//            HienThiLoaiSach();
//        }
    AddCacLoaiSach acls = new AddCacLoaiSach(this, rootPaneCheckingEnabled);
    acls.setVisible(true);
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        selectedIndex = tbLoaiSach.getSelectedRow();
        if(ListLS.size() == 0){
            JOptionPane.showMessageDialog(this, "chưa có sách trong bảng !!! hãy thêm sách để sửa");
        }else if(selectedIndex == -1){
            JOptionPane.showMessageDialog(this, "Hãy chọn sách để sửa");
        }else{
            EditLoaiSach els = new EditLoaiSach(this, rootPaneCheckingEnabled);
            els.setEditData(ListLS.get(selectedIndex));
            els.setVisible(true);
//            HienThiLoaiSach();
         
        }
        HienThiLoaiSach();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void tbLoaiSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbLoaiSachMouseClicked
        // TODO add your handling code here:
//        DefaultTableModel DTM = (DefaultTableModel) tbLoaiSach.getModel();
//        
//        int SelectedRow = tbLoaiSach.getSelectedRow();
//        txtID.setText(DTM .getValueAt(SelectedRow, 0).toString());
//        txtID.setEditable(false);
//        txtMaSach.setText(DTM .getValueAt(SelectedRow, 1).toString());
//        txtTenSach.setText(DTM .getValueAt(SelectedRow, 2).toString());
//        txtDonGia.setText(DTM .getValueAt(SelectedRow, 3).toString());
//        txtSoLuong.setText(DTM .getValueAt(SelectedRow, 4).toString());
//        txtNgayXuatBan.setText(DTM .getValueAt(SelectedRow, 5).toString());
//
//        cbLoaiSach.setSelectedItem(DTM .getValueAt(SelectedRow, 6).toString());
//        cbNhaXuatBan.setSelectedItem(DTM .getValueAt(SelectedRow, 7).toString());
    }//GEN-LAST:event_tbLoaiSachMouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
         selectedIndex = tbLoaiSach.getSelectedRow();
        if(selectedIndex == 0){
            JOptionPane.showMessageDialog(this, "Hay Chon Sach De Xoa");
        }
        else{
            LoaiSach ls = ListLS.get(selectedIndex);
            int option = JOptionPane.showConfirmDialog(this, "Ban co muon xoa Loai Sach Nay chu !!!");
            System.out.print("option: " + option);
            if(option == 0){
                DAOLoaiSach.DeleteLoaiSach(ls);
                HienThiLoaiSach();
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
            try{
         String input = JOptionPane.showInputDialog(this, "Nhap Ten De tim Kiem");
     if (input.length() > 0) {
            ListLS = DAOLoaiSach.TimKiemTheoTen(input);
            tableModel.setRowCount(0);
            for(LoaiSach ls: ListLS){//ham for-each duyet qua cac pt ma khong can index;
            //Dữ liệu được thêm vào bằng cách sử dụng addRow
          tableModel.addRow(new Object[]{ls.getID(), ls.getMaSach(), ls.getTenSach(), ls.getDonGia(), ls.getSoLuong(), ls.getNgayXuatBan(), ls.getLoaiSach(), ls.getNhaXuatBan(),});
                }
//            JOptionPane.showMessageDialog(this, "tim thanh cong !!! ");
            }  
        }
     catch(Exception ex){
         JOptionPane.showMessageDialog(this, "tim khong thanh cong !!! ");
        }
//        try {
//            String input = JOptionPane.showInputDialog(this, "Nhap Ten De tim Kiem");
//
//            if (input.length() > 0) {
//                ListLS = DAOLoaiSach.TimKiemTheoTen(input);
//                tableModel.setRowCount(0);
//                for (LoaiSach ls : ListLS) {
//                    //ham for-each duyet qua cac pt ma khong can index;
//                    //Dữ liệu được thêm vào bằng cách sử dụng addRow
//                    tableModel.addRow(new Object[]{tableModel.getRowCount() + 1, ls.getID(), ls.getMaSach(), ls.getTenSach(), ls.getDonGia(), ls.getSoLuong(), ls.getNgayXuatBan(), ls.getLoaiSach(), ls.getNhaXuatBan()});
//                }
//            }
//        } catch (Exception ex) {
//            JOptionPane.showMessageDialog(this, "Tim Kiem Khong Thanh Cong");
//        }
    }//GEN-LAST:event_btnTimKiemActionPerformed
    

    private void btnQuayLaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiActionPerformed
        // TODO add your handling code here:
        QuanLy ql = new QuanLy();
        ql.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnQuayLaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CacLoaiSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CacLoaiSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CacLoaiSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CacLoaiSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                 new CacLoaiSach().setVisible(true);
            }

        });
        
    }
    public void Editls(LoaiSach ls){
           DAOLoaiSach.UpdateSach(ls);
           HienThiLoaiSach();
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuayLai;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTable tbLoaiSach;
    // End of variables declaration//GEN-END:variables

    


}
